cliente = input("Digite o nome do cliente: ")
dia = input("Digite o dia de vencimento: ")
mês = input("Digite o mês de vendimento: ")
fatura = input("Digite o valor da fatura: ")
print("Olá, " + cliente + "\nA sua fatura com vencimento em " + dia + " de " + mês + " no valor de R$ " + fatura + " está fechada.")